_BASE_: Base-PointRend-Semantic-FPN.yaml
MODEL:
  WEIGHTS: detectron2://ImageNetPretrained/MSRA/R-101.pkl
  RESNETS:
    DEPTH: 101
  SEM_SEG_HEAD:
    NUM_CLASSES: 182
  POINT_HEAD:
    NUM_CLASSES: 182
    TRAIN_NUM_POINTS: 1024
    SUBDIVISION_NUM_POINTS: 4096
DATASETS:
  TRAIN: ("cocostuff_train2017",)
  TEST: ("cocostuff_val2017",)
SOLVER:
  BASE_LR: 0.004
  STEPS: (40000, 55000)
  MAX_ITER: 65000
  IMS_PER_BATCH: 2
INPUT:
  MIN_SIZE_TRAIN: (512, 768)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 512
  MAX_SIZE_TRAIN: 1024
  MAX_SIZE_TEST: 1024
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512, 1024)
    SINGLE_CATEGORY_MAX_AREA: 0.75
  COLOR_AUG_SSD: True
DATALOADER:
  NUM_WORKERS: 1
OUTPUT_DIR: "cocostuff_pointrend_outputs_2"
